import katex from 'katex';

/**
 * Pre-processes HTML generated by rich text editors (like TinyMCE) to render KaTeX math.
 * Rich text editors often wrap text in <p> tags, meaning a multi-line math block like:
 * $$
 * x = 1
 * $$
 * Becomes: <p>$$</p><p>x = 1</p><p>$$</p>
 * Standard DOM-based renderers (like renderMathInElement) fail here because the start
 * and end delimiters are in different block nodes.
 *
 * This function uses regex on the raw HTML string to find delimiter pairs, safely extracts
 * the inner text (stripping HTML tags that the editor might have injected), and replaces
 * the entire block with rendered KaTeX HTML.
 */
export function renderMathInRawHtml(html: string): string {
  if (!html) return html;

  let processed = html;

  // Delimiters to process (ordered by priority: block first, then inline)
  const blocks = [
    { left: '$$', right: '$$', display: true },
    { left: '\\[', right: '\\]', display: true },
    { left: '\\(', right: '\\)', display: false },
    { left: '$', right: '$', display: false }
  ];

  for (const block of blocks) {
    // Escape regex characters in delimiters
    const escapeRegExp = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const leftMatch = escapeRegExp(block.left);
    const rightMatch = escapeRegExp(block.right);

    // Regex to match delimiter pairs.
    // For single $, we use negative lookbehind/lookahead to avoid matching $$.
    let regexStr = `${leftMatch}([\\s\\S]+?)${rightMatch}`;
    if (block.left === '$' && block.right === '$') {
      regexStr = `(?<!\\$)\\$([^$]+?)\\$(?!\\$)`;
    }

    const regex = new RegExp(regexStr, 'g');

    processed = processed.replace(regex, (match, innerHtml) => {
      // 1. Strip all HTML tags that the rich text editor may have injected
      // e.g. <p>x=1</p> becomes x=1
      let latex = innerHtml.replace(/<[^>]+>/g, ' ');
      
      // 2. Decode HTML entities that the editor may have escaped
      latex = latex
        .replace(/&nbsp;/g, ' ')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'");

      try {
        return katex.renderToString(latex.trim(), {
          displayMode: block.display,
          throwOnError: false
        });
      } catch (e) {
        console.error("KaTeX render error:", e);
        return match;
      }
    });
  }

  return processed;
}
